Serval:
  energy: 50
  baseSpeed: 106
  _currentSpeed: 106
  maxEnergy: 100
  energyRegen: 0

Bronya:
  energy: 55
  baseSpeed: 105
  _currentSpeed: 134
  maxEnergy: 110
  energyRegen: 19.4

Sushang:
  energy: 50
  baseSpeed: 107
  _currentSpeed: 135
  maxEnergy: 100
  energyRegen: 0

Seele:
  energy: 60
  baseSpeed: 115
  _currentSpeed: 152
  maxEnergy: 120
  energyRegen: 0

Tingyun:
  energy: 65
  baseSpeed: 112
  _currentSpeed: 125
  maxEnergy: 130
  energyRegen: 0

Sparkle:
  energy: 50
  baseSpeed: 101
  _currentSpeed: 135
  maxEnergy: 110
  energyRegen: 19.4

# Character
# baseSpeed
# maxEnergy